### ISSUE TITLE
Brutalism CSS

### ISSUE THREAD

**Issue by StringentDev** [hackermondev/daniel.is-a.dev#1]
Having pure white and black is not recommended for user experience as it can slow down a user's reading stamina and it can cause eyestrain.

See these sources for more information:
 - https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/
 - https://graphicdesign.stackexchange.com/questions/25356/why-not-use-pure-black-000-and-pure-white-fff
 - https://ux.stackexchange.com/questions/23965/is-there-a-problem-with-using-black-text-on-white-backgrounds

**Comment by hackermondev** [comment]
thanks for this! i've changed the colors so it can be easier to read.

**Comment by StringentDev** [comment]
@hackermondev You're welcome :D, it looks a lot better.
